name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: make test
